Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere









# Section A *(2 Marks each)*

## NumPy (Numerical Python)

### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [1]:
import numpy as np

In [2]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:\n", arr_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# Write a NumPy function to create an array with random values of shape [3,4]
rand_arr = np.random.rand(3, 4)

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
zero_arr = np.zeros((3, 4))

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
ones_arr = np.ones((3, 4))


In [4]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
evenly_spaced = np.arange(0, 10, 2)


### Basic array operations
- algebraic operations
- logical operations

In [5]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [6]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
add_ab = np.add(a, b)
sub_ab = np.subtract(a, b)
mul_ab = np.multiply(a, b)
div_ab = np.divide(a, b)


In [7]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
sum_a_ax0 = np.sum(a, axis=0)

# Write a NumPy function to get the sum of the array 'a' along axis=1
sum_a_ax1 = np.sum(a, axis=1)


In [8]:
# Write a NumPy function to reverse the array 'a'
rev_a = np.flip(a)

# Write a NumPy function to reverse the array 'a' along axis=0
rev_a_ax0 = np.flip(a, axis=0)

# Write a NumPy function to reverse the array 'a' along axis=1
rev_a_ax1 = np.flip(a, axis=1)


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [9]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [10]:
# Write a NumPy function to sort the array 'a'
sort_a = np.sort(a, axis=None) # Flattens before sorting

# Write a NumPy function to sort the array 'a' along axis=0
sort_a_ax0 = np.sort(a, axis=0)

# Write a NumPy function to sort the array 'a' along axis=1
sort_a_ax1 = np.sort(a, axis=1)

# Write a NumPy function to sort the array 'a' in descending order along axis=0
sort_a_desc_ax0 = np.sort(a, axis=0)[::-1]


In [11]:
# Write a NumPy function to argsort the array along axis=0
argsort_a_ax0 = np.argsort(a, axis=0)

# Write a NumPy function to argsort the array along axis=1
argsort_a_ax1 = np.argsort(a, axis=1)


In [12]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
concat_ab = np.concatenate((a, b), axis=None)

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
concat_ab_ax0 = np.concatenate((a, b), axis=0)

# Note: You can do the same function using stacking, discover and try that :)
stacked_ab = np.vstack((a, b))


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [13]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [14]:
# Write a NumPy function to get the Number of dimensions
ndim_a = a.ndim

# Write a NumPy function to get the Shape of the array
shape_a = a.shape

# Write a NumPy function to get the Size of the array
size_a = a.size


In [15]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
reshaped_a = a.reshape((1, 9))


In [16]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this
new_axis_1 = a[:, :, np.newaxis]
new_axis_2 = np.expand_dims(a, axis=2)

### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [17]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [18]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
idx_int = a[1]           # Integer
idx_tuple = a[1, 2]      # Tuple
idx_range = a[0:2, 1:3]  # Range


In [19]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
cond_1 = a[a > 4]

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
cond_2 = a[(a > 4) & (a % 2 == 0)]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [20]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [21]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
a_copy = a.copy()
a_copy += 1
print(a_copy)


[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [22]:
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

import ssl
from urllib.request import urlopen

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
context = ssl._create_unverified_context()
data = urlopen(url, context=context)
iris_2d = np.genfromtxt(data, delimiter=',', dtype = 'float', usecols=(0,1,2,3), encoding='utf-8')

#### Basic Data Analysis

In [23]:
# Write a Pandas function to drop rows that contain a missing value.
import pandas as pd
df_iris2d = pd.DataFrame(iris_2d, columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])
df_iris2d_clean = df_iris2d.dropna()


In [24]:
# Write a Pandas function to find the correlation between the first two columns.
correlation = df_iris2d_clean['sepal_length'].corr(df_iris2d_clean['sepal_width'])


In [25]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
mean_col3 = df_iris2d_clean['petal_length'].mean()
median_col3 = df_iris2d_clean['petal_length'].median()
std_col3 = df_iris2d_clean['petal_length'].std()


In [26]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
volume_np = (np.pi * iris_2d[:, 2] * (iris_2d[:, 0]**2)) / 3
volume_expanded = volume_np[:, np.newaxis]            # 1. Introduce new dimension
iris_2d_new = np.hstack((iris_2d, volume_expanded))   # 2. Add the new column

# Pandas approach (Simplest):
df_iris2d_clean['volume'] = (np.pi * df_iris2d_clean['petal_length'] * (df_iris2d_clean['sepal_length']**2)) / 3

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [27]:
x = np.arange(4, dtype=np.int64)
ones_x = np.ones_like(x)

Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [28]:
x = np.arange(1, 10)
split_arrays = np.split(x, [4, 6])
# Splits at indices 4 and 6, resulting in arrays of lengths 4, 2, and 3.

Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [29]:
x = np.random.randint(0, 10, (2, 5))
max_vals = x.max(axis=1)
max_idx = x.argmax(axis=1)
min_vals = x.min(axis=1)
min_idx = x.argmin(axis=1)

### Pandas

Run the following load command and solve the following questions

In [30]:
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris = np.genfromtxt(url, delimiter=',', dtype='object')
# names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

import ssl
import pandas as pd
from urllib.request import urlopen
from io import StringIO

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
context = ssl._create_unverified_context()
data = urlopen(url, context=context)
text = data.read().decode('utf-8')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris_df = pd.read_csv(StringIO(text),header=None,names=names)

Q4 Write a Pandas function to find the count of unique species.

In [31]:
unique_species_count = iris_df['species'].nunique()

# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [32]:
bins = [0, 3, 5, np.inf]
labels = ['small', 'medium', 'large']
iris_df['petal_length_binned'] = pd.cut(iris_df['petallength'], bins=bins, labels=labels, right=False)

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [33]:
most_freq_petal_length = iris_df['petallength'].mode()[0]